Calendar/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

plutus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import RedirectView
#from machina import urls as machina_urls
from django.conf.urls.static import static


admin.site.site_header = 'Provisn Administration'
admin.site.site_title = 'Provisn Administration'

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('cpanel/', admin.site.urls),
    path('cpanel/doc/', include('django.contrib.admindocs.urls')),
    path('member/', include('userdashboard.urls')),
    path('', include('frontpage.urls')),
    path('', include('django.contrib.auth.urls')),
    url(r'^accounts/login/$', RedirectView.as_view(pattern_name='login', permanent=False)),
    path('cryptapi/', include('cryptapi.urls')),
    url(r'^accounts/passwordreset/', include('password_reset.urls')),
    #path('forum/', include(machina_urls)),
    path('calendar/', include('Calendar.urls')),

#    url(r'^member/', include('django_private_chat.urls')),

    # In case unwanted redirections occur to /user/* uncomment and update the following line
    #path('user/*/', RedirectView.as_view(pattern_name='user_area')),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .settings import DEBUG
if DEBUG == True:
    urlpatterns += staticfiles_urlpatterns()

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import plutus.settings as settings
if settings.DEBUG == True:
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Calendar/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    tags = TaggableManager(blank=True)

    @property
    def get_html_url(self):
        url = reverse('userdashboard:DetailsEvents', args=(self.id,))
        return f'<a href="{url}"> <div class="event">{self.title}</div> </a>'

Calendar/forms.py
from django.forms import ModelForm, DateInput
from userdashboard.models import BlockchainEvent as Event
from django import forms
from django.utils.safestring import mark_safe


class EventForm(ModelForm):

    COLOR_CHOICES = (
        ('event_color_brown', 'Coin Event (Brown)'),
        ('event_color_blue', 'Location Based Event (Blue)'),
        ('event_color_green', 'Provisn Event (Green)'),
    )

    color_class = forms.ChoiceField(choices=COLOR_CHOICES)
    title = forms.CharField(required=True)
    date_of_event = forms.DateTimeField(
        label_suffix=mark_safe('<small> (D/M/Y H:M <small>24H</small>)</small>'),
        input_formats=['%d/%m/%Y %H:%M',],
        required=True,
        widget=forms.DateTimeInput(format='%d/%m/%Y %H:%M', attrs={'type': 'datetime-local'})
    )

    class Meta:
        model = Event
        fields = ['title', 'date_of_event', 'color_class', 'text', 'tags']

Calendar/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.utils.safestring import mark_safe
import calendar
from django.urls import reverse

#from .models import *
from userdashboard.models import BlockchainEvent as Event
from .utils import Calendar
from .forms import EventForm


def index(request):
    return HttpResponse('hello')

class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

def event(request, event_id=None):
    if not request.user.is_superuser or not request.user.is_staff:
        return HttpResponseRedirect(reverse('cal:calendar'))

    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()

    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request, 'cal/event.html', {'form': form})

Calendar/templates/cal/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
          crossorigin="anonymous">
    <link href="{% static 'css/app.css' %}" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/member_area.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
    <title>Provisn Calendar</title>
</head>
<body>

{% block content %}
{% endblock %}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

{% block script %}
{% endblock %}
</body>
</html>

Calendar/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block title %}
Event Calendar
{% endblock %}

{% block content %}
<div class="clearfix2">
	<a class="btn btn-primary left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-primary right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
    {% if user.is_superuser or user.is_staff %}
		<a class="btn btn-add waves-effect waves-light width-md" href="{% url 'cal:event_new' %}" style="margin-left: 25px; font-size: 14px; border: 0;"> Add new event</a>
	{% endif %}
</div>




        <!-- Start Content-->
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">

                        <h3 class="page-title">{{ pagetitle }}</h3>
                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row">




                        {{ calendar }}









			</div>
		</div>


{% endblock %}

Calendar/templates/cal/event.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-primary left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}