Calendar/urls.py
from django.conf.urls import url
from . import views

app_name = 'cal'
urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^calendar/$', views.CalendarView.as_view(), name='calendar'),
    url(r'^event/new/$', views.event, name='event_new'),
	url(r'^event/edit/(?P<event_id>\d+)/$', views.event, name='event_edit'),
]

plutus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic import RedirectView
#from machina import urls as machina_urls
from django.conf.urls.static import static


admin.site.site_header = 'Provisn Administration'
admin.site.site_title = 'Provisn Administration'

urlpatterns = [
    path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('cpanel/', admin.site.urls),
    path('cpanel/doc/', include('django.contrib.admindocs.urls')),
    path('member/', include('userdashboard.urls')),
    path('', include('frontpage.urls')),
    path('', include('django.contrib.auth.urls')),
    url(r'^accounts/login/$', RedirectView.as_view(pattern_name='login', permanent=False)),
    path('cryptapi/', include('cryptapi.urls')),
    url(r'^accounts/passwordreset/', include('password_reset.urls')),
    #path('forum/', include(machina_urls)),
    path('calendar/', include('Calendar.urls')),

#    url(r'^member/', include('django_private_chat.urls')),

    # In case unwanted redirections occur to /user/* uncomment and update the following line
    #path('user/*/', RedirectView.as_view(pattern_name='user_area')),
]

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .settings import DEBUG
if DEBUG == True:
    urlpatterns += staticfiles_urlpatterns()

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import plutus.settings as settings
if settings.DEBUG == True:
    urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userdashboard/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url
from rest_framework.authtoken.views import obtain_auth_token

# Well this explains itself i think
# path(uri, view method, name (e.g. grabbing urls));
# app_name = 'userdashboard'

urlpatterns = [
    url(r'^', include('TelegramHandler.urls', namespace='TelegramHandler')),
    url(r'^', include('ContentScraper.urls', namespace='ContentScraper')),

    path('', views.userDashboard, name="user_area"),
    path('beams/', views.userBeams, name='user_beams'),
    path('events/', views.userBlockchainEvents, name='user_events'),
    path('news/', views.userNews, name="user_news"),
    path('ai/', views.userAI, name='user_ai'),
    path('technical_analysis/', views.userTechnicalAnalysis, name='user_technical_analysis'),
    path('token_spotlight/', views.userTokenWatchlist, name='user_token_watchlist'),

    path('invite/', views.FriendInvitationOverview, name='FriendInvitationOverview'),

    url(r'^search/$', views.search, name='search'),

    path('account/payment/', views.order_creation_view, name='order_creation_view'),
    path('account/paymentc', views.credit_card_payment_charge, name='credit_card_payment_charge'),
    path('account/paymentc/success', views.credit_card_payment_charge_successful, name='credit_card_payment_charge_successful'),
    path('account/paymentc/cancelled', views.credit_card_payment_charge_cancelled, name='credit_card_payment_charge_cancelled'),

    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    path('logout/', views.logOut, name='logout'),
    path('account/', views.member, name='member'),
    path('account/payout', views.payout, name='payout'),
    path('account/cancel_subscription', views.cancel_subscription, name='cancel_user_subscription'),
    path('staff/', views.userAdminTools, name='user_admin_tools'),
    path('settings/', views.userSettings, name='user_settings'),
    path('changelog/', views.userChangelog, name='user_changelog'),

    path('invite_friends/', views.send_friend_invitation, name='friend_inviter'),

    path('export/csv/trial_users', views.export_trial_users_as_csv, name='export_users_trial'),
    path('export/csv/subscribed_users', views.export_subscribed_users_as_csv, name='export_users_subscribed'),
    path('export/csv/all', views.export_all_users_as_csv, name='export_users_all'),
    path('export/csv/sub_and_trial_users', views.export_subscribed_and_trial_users_as_csv, name='export_users_sub_and_trial'),

    path('staff/extend_subscription', views.staff_prolong_subscription, name='staff_extend_subscription'),
    path('staff/test_payment_successful', views.test_order_view, name='staff_test_payment_successful'),

    path('bugreporter', views.BugReporter, name='BugReporter'),

    path('beams/<int:pk>/', views.DetailsBeams, name='DetailsBeams'),
    path('events/<int:pk>/', views.DetailsEvents, name='DetailsEvents'),
    path('news/<int:pk>/', views.DetailsBN, name='DetailsNews'),
    path('ai/<int:pk>/', views.DetailsAIEntry, name='DetailsAI'),
    path('technical_analysis/<int:pk>/', views.DetailsTA, name='DetailsTA'),
    path('technical_analysis_cn/<int:pk>/', views.DetailsTA_cn, name='DetailsTA_m'),
    path('technical_analysis_f/<int:pk>/', views.DetailsTA_f, name='DetailsTA_f'),
    path('technical_analysis_ka/<int:pk>/', views.DetailsTA_ka, name='DetailsTA_ka'),
    path('technical_analysis_am/<int:pk>/', views.DetailsTA_am, name='DetailsTA_am'),
    path('token_spotlight/<int:pk>/', views.DetailsTW, name='DetailsTW'),

    path('beams/new/', views.NewBeams, name='NewBeams'),
    path('events/new/', views.NewEvents, name='NewEvents'),
    path('news/new/', views.NewBN, name='NewBN'),
    path('ai/new/', views.NewAIEntry, name='NewAIEntry'),
    path('technical_analysis/new/', views.NewTA, name='NewTA'),
    path('token_spotlight/new/', views.NewTW, name='NewTW'),

    url(r'^beams/(?P<pk>\d+)/publish/$', views.PublishBeams, name='PublishBeams'),
    url(r'^events/(?P<pk>\d+)/publish/$', views.PublishEvents, name='PublishEvents'),
    url(r'^news/(?P<pk>\d+)/publish/$', views.PublishBN, name='PublishNews'),
    url(r'^ai/(?P<pk>\d+)/publish/$', views.PublishAI, name='PublishAI'),
    url(r'^technical_analysis/(?P<pk>\d+)/publish/$', views.PublishTA, name='PublishTA'),
    url(r'^token_spotlight/(?P<pk>\d+)/publish/$', views.PublishTW, name='PublishTW'),

    path('beams/drafts/', views.DraftsBeams, name='DraftsBeams'),
    path('events/drafts/', views.DraftsEvents, name='DraftsEvents'),
    path('news/drafts/', views.DraftsBN, name='DraftsBN'),
    path('ai/drafts/', views.DraftsAI, name='DraftsAIEntry'),
    path('technical_analysis/drafts/', views.DraftsTA, name='DraftsTA'),
    path('token_spotlight/drafts/', views.DraftsTW, name='DraftsTW'),

    url(r'^beams/(?P<pk>\d+)/comment/$', views.AddCommentToBeam, name='AddCommentBeams'),
    url(r'^events/(?P<pk>\d+)/comment/$', views.AddCommentToEvent, name='AddCommentEvent'),
    url(r'^news/(?P<pk>\d+)/comment/$', views.AddCommentToBN, name='AddCommentNews'),
    url(r'^ai/(?P<pk>\d+)/comment/$', views.AddCommentToAIEntry, name='AddCommentAI'),
    url(r'^technical_analysis/(?P<pk>\d+)/comment/$', views.AddCommentToTA, name='AddCommentTA'),
    url(r'^token_spotlight/(?P<pk>\d+)/comment/$', views.AddCommentToTW, name='AddCommentTW'),

    #url(r'^member/beams/(?P<pk>\d+)/remove/$', ..., name='RemoveBeams'),
    #url(r'^member/beams/(?P<pk>\d+)/comment')

    #url(r'^/messenger', views.MessagesOverview, name='messenger_overview')

    path('referral/pay_offs', views.referral_pay_off_list, name='ReferralPayOffs'),

    path('test_confirmed_page', views.test_activated_page, name='test_confirmed_page'),
    path('test_user_notification', views.test_user_notification, name='test_user_notification'),

    ### REST API
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),

    path('api/link_preview', views.Preview_Links.as_view(), name='link_preview'),
    path('api/get_all_crypto_currencies', views.GetAllCryptoCurrencies.as_view(), name='get_all_crypto_currencies'),
    path('api/get_crypto_currency_price_performance', views.GetCryptoCurrencyPricePerformance.as_view(), name='get_crypto_currency_price_performance'),
    path('api/get_crypto_currency_info', views.GetCryptoCurrencyInfo.as_view(), name='get_crypto_currency_info'),
    path('api/get_crypto_currency_market_quotes', views.GetCryptoCurrencyMarketQuotes.as_view(), name='get_crypto_currency_market_quotes'),
    path('api/dashboard_events', views.GetDashboardEvents.as_view(), name='dashboard_events'),
    path('api/payment_status', views.GetPaymentStatus.as_view(), name='payment_status'),
    path('api/latest_listings', views.GetLatestListings.as_view(), name='latest_listings'),
    path('api/test-coinpaprika', views.TestCoinpaprika.as_view(), name='test-coinpaprika'),
    # Stripe Webhook
    path('api/sw', views.stripe_webhook, name='sw'),

]

userdashboard/templates/user_area/user/Content_Pages/AI-Article.html
{% extends 'user_area/base.html' %}
{% load static %}
{% block content %}

<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">
                        
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <h3 class="page-title">AI Signal call</h3>
                    </div>
                </div>
            </div>
            <!-- end page title -->

            <!-- Start Content -->
            <div class="row">
                <div class="col-md-6">
                    <div class="card-box">
                        <h1>{% if post.title %} {{ post.title }} {% endif %}</h1>
                        <p class="text-muted mb-0">
                                    
                            {{ post.get_text_field|safe }}

                        </p>

                        <div class="sc-gauge">
                            <div class="sc-background">
                                <div class="sc-percentage {{ GaugeClass }}"></div>
                                <div class="sc-mask"></div>
                                <span class="sc-value">{{ GaugePercent }}%</span>
                            </div>
                            <span class="sc-min">0</span>
                            <span class="sc-max">100</span>
                        </div>
                                    
                        <div class="clearfix"></div>
                    </div>
                    <!-- end card-box-->

                </div>

                    
            </div>
            <!-- end card-box-->



        </div>

        <!-- ============================================================== -->
        <!-- End Page content -->
        <!-- ============================================================== -->

    </div>
    <!-- END wrapper -->
</div>
<style type="text/css">

            .sc-percentage { transform:rotate({{ GaugeDegree }}deg); transform-origin:top center; }

</style>
{% endblock %}

userdashboard/templates/user_area/user/Content_Pages/AI.html
{% extends 'user_area/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box mb30">

                        <h3 class="page-title">{{ pagetitle }}</h3>
                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row grid beams-padding" style="height: fit-content">  <!-- col-3 09-29 -->

                {% for item in items %}
                    <!-- <div class="col-md-3 grid-item no-border"> -->
                    <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12 grid-item no-border" style="margin-bottom: 24px;">  <!-- col-3 09-29 -->
                        {% if item.title %}
                            <h1 class="dashboardTitle">
                                {{ item.title }}
                            </h1>
                        {% endif %}
                        <div class="card-box-ai">
                            <h3 class="float-right">
                                {% if item.coin.coin_icon %}
                                    <img class="cryptocurrency-icons-content-list-page" src="{{ item.coin.coin_icon.url }}"/>
                                {% endif %}
                                {{ item.coin.short_name }}
                            </h3>
                            <div class="sc-gauge">
                                <div class="sc-background">
                                    <div style="transform:rotate({{ item.get_percentage_value_in_deg }}deg); transform-origin:top center;" class="sc-percentage {{ item.get_gauge_class }}"></div>
                                    <div class="sc-mask2"></div>
                                    <span class="sc-value">{{ item.get_percentage_value }}%</span>
                                </div>
                                <span class="sc-min">0</span>
                                <span class="sc-max">100</span>
                            </div>
                            <div class="text-muted mb-0 ai-text">
                                {{ item.get_text_field|safe }}
                            </div>
                            <small class="published">
                                {{ item.published_date|naturaltime }}
                            </small>

                        </div>
                    </div>
                {% endfor %}

                <div class="col-12 margin-auto" style="height:100px;"><!-- Don't ask why height:100px; without this tag at all, the read more stopped working -->


                    <!-- <ul class="pagination">
                                                    <li class="page-item">
                                                    {% if items.has_previous %}
                                                        <a class="page-link" href="?page=1" aria-label="Previous">
                                                            <span aria-hidden="true">‹‹</span>
                                                            <span class="sr-only">First</span>
                                                        </a>
                                                    </li>
                                                    <li class="page-item">
                                                        <a class="page-link" href="?page={{ items.previous_page_number }}" aria-label="Previous">
                                                            <span aria-hidden="true">Prev</span>
                                                            <span class="sr-only">Prev</span>
                                                        </a>
                                                    {% endif %}
                                                    </li>
                                                    <li class="page-item active"><a class="page-link" href="#">{{ items.number }} of {{ items.paginator.num_pages }}</a></li>

                                                    {% if items.has_next %}
                                                    <li class="page-item">
                                                        <a class="page-link" href="?page={{ items.next_page_number }}" aria-label="Next">
                                                            <span aria-hidden="true">Next</span>
                                                            <span class="sr-only">Next</span>
                                                        </a>
                                                    </li>
                                                     <li class="page-item">
                                                        <a class="page-link" href="?page={{ items.paginator.num_pages }}" aria-label="Last">
                                                            <span aria-hidden="true">››</span>
                                                            <span class="sr-only">Last</span>
                                                        </a>
                                                    </li>
                                                    {% endif %}
                                                </ul> --!>


                </div>



            </div> <!-- container-fluid -->
        </div> <!-- content -->



    </div>


    <!-- ============================================================== -->
    <!-- End Page content -->
    <!-- ============================================================== -->



</div>


{% endblock %}

userdashboard/templates/user_area/user/Content_Pages/Beam.html
{% extends 'user_area/base.html' %}
{% load static %}
{% load humanize %}
{% block content %}

<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">

                        <h3 class="page-title">Beam</h3>
                    </div>
                    {% if user.is_superuser or user.is_staff %}
                        {% if not post.published_date %}
                        <a style="" class="btn btn-primary" href="{% url 'PublishBeams' pk=post.pk %}">Publish</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            <!-- end page title -->

            <!-- Start Content -->
            <div class="row">
                <div class="col-3"  style="">
                        {% if post.pair %}<h4 class="w-100 dashboard-beams-content-header">{{ post.pair }}</h4>{% endif %}
                        <div class="dashboardblock-entry">
                            <div class="dashboard-beams-content">
                                {% if post.entry %}
                                <div class="w-100">
                                    Entry:
                                    <span class="float-right no-list">{{ post.entry|safe }}</span>
                                    <div class="clearfix"></div>
                                </div>
                                {% endif %}
                                {% if post.targets %}
                                <div class="w-100">
                                    Targets:
                                    <span class="float-right no-list">{{ post.targets|linebreaksbr|safe }}</span>
                                    <div class="clearfix"></div>
                                </div>
                                {% endif %}
                                {% if post.stop_loss %}
                                <div class="w-100">
                                    Stop Loss:
                                    <span class="float-right no-list">{{ post.stop_loss|safe }}</span>
                                    <div class="clearfix"></div>
                                </div>
                                {% endif %}
                                <div class="footer-beam">
                                    <div class="beam-exchange">{{ post.exchange }}</div><div class="date-beam">  {{ post.published_date|naturaltime}}  </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- end row -->
            </div>
            <!-- end card-box-->
        </div>
    </div>
</div>

{% endblock %}

userdashboard/templates/user_area/user/Content_Pages/Beams.html
{% extends 'user_area/base.html' %}
{% load static %}
{% load humanize %}
{% static "" as baseUrl %}
{% block content %}

<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">
        <!-- Start Content-->
        <div class="container-fluid">
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box">
                        <h3 class="page-title">
                            {{ pagetitle }}
                            {% if user.is_superuser or user.is_staff %}
                            <a href="{% url 'NewBeams' %}"><i class="mdi mdi-pencil-plus-outline"></i></a>
                            <a href="{% url 'DraftsBeams' %}" class="btn btn-primary"><b>Drafts </b></a>
                            {% endif %}
                        </h3>
                    </div>
                </div>
            </div>
            <!-- end page title -->

            <div class="row grid beams-padding" style="height: fit-content; margin-top: 10px;">  <!-- col-3 09-29 -->
                <div class="grid-sizer"></div>
                {% for item in items %}
                <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12" style="margin-bottom: 24px;">  <!-- col-3 09-29 -->
                    {% if item.pair %}
                    {% if user.is_superuser or user.is_staff %}
                    <a href='{% url "DetailsBeams" pk=item.pk %}'>
                        {% endif %}
                        <h4 class="w-100 dashboard-beams-content-header {{ item.color_class }}">
                            {{ item.pair }}
                        </h4>
                        {% if user.is_superuser or user.is_staff %}
                    </a>
                    {% endif %}
                    {% endif %}
                    <div class="dashboardblock-entry box-shadow dark-grey">
                        <div class="dashboard-beams-content">
                            {% if item.entry %}
                            <div class="w-100" style=" border-bottom: 1px solid #303030; padding-bottom: 7px;">
                                Entry:
                                <span class="float-right no-list beam-data">{{ item.entry|linebreaksbr|safe }}</span>
                                <div class="clearfix"></div>
                            </div>
                            {% endif %}
                            {% if item.targets %}
                            <div class="w-100 target-beam"
                                style="    border-bottom: 1px solid #303030; margin-top:7px; padding-bottom: 7px;">
                                Targets:
                                <span class="float-right no-list beam-data">{{ item.targets|linebreaksbr|safe }}</span>
                                <div class="clearfix"></div>
                            </div>
                            {% endif %}
                            {% if item.stop_loss %}
                            <div class="w-100" style=" margin-top:7px; ">
                                Stop Loss:
                                <span
                                    class="float-right no-list beam-data">{{ item.stop_loss|linebreaksbr|safe }}</span>
                                <div class="clearfix"></div>
                            </div>
                            {% endif %}
                            <div class="footer-beam">
                                <div class="beam-exchange">{{ item.exchange }}</div>
                                <div class="date-beam"> {{ item.published_date|naturaltime}} </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% if items.paginator.num_pages > 2 %}
                <div class="col-12 margin-auto grid-item" style="height:100px;">
                    <!-- Don't ask why height:100px; without this tag at all, the read more stopped working -->
                    <ul class="pagination">
                        <li class="page-item">
                            {% if items.has_previous %}
                            <a class="page-link" href="?page=1" aria-label="Previous">
                                <span aria-hidden="true">‹‹</span>
                                <span class="sr-only">First</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ items.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">Prev</span>
                                <span class="sr-only">Prev</span>
                            </a>
                            {% endif %}
                        </li>
                        <li class="page-item active"><a class="page-link" href="#">{{ items.number }} of
                            {{ items.paginator.num_pages }}</a></li>
                        {% if items.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ items.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">Next</span>
                                <span class="sr-only">Next</span>
                            </a>
                        </li>
                        <li class="page-item">
                            <a class="page-link" href="?page={{ items.paginator.num_pages }}" aria-label="Last">
                                <span aria-hidden="true">››</span>
                                <span class="sr-only">Last</span>
                            </a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
                {% endif %}
            </div>
        </div> <!-- container-fluid -->
    </div> <!-- content -->
</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

{% endblock %}

userdashboard/templates/user_area/user/Content_Pages/Events.html
{% extends 'user_area/base.html' %}
{% block content %}

<div class="content-page">
    <!-- Header -->
    <div class="content">
        <!-- Start Content-->
        <div class="container-fluid">
            <!-- start page title -->
            <div class="row">
                <div class="col-12">
                    <div class="page-title-box mb30">
                        <h3 class="page-title">{{ pagetitle }} - {{ subHeader }} </h3>
                    </div>
                </div>
            </div>
            <!-- end page title -->
            <!-- Actual Content -->
            <div class="row" style="padding: 0 ; margin: 0; min-width: 540px;">
                {% if PageRefAddContent == 'NewBlockchainEvents' %}
                <script type="application/javascript">
                    function resizeIFrameToFitContent(iFrame) {
                        iFrame.width = iFrame.contentWindow.document.body.scrollWidth;
                        iFrame.height = iFrame.contentWindow.document.body.scrollHeight + 30;
                    }
                    window.addEventListener('DOMContentLoaded', function (e) {
                        var iFrame = document.getElementById('calendar_frame');
                        resizeIFrameToFitContent(iFrame);
                    });
                </script>
                <div class="card-box w-100">
                    <iframe id="calendar_frame" class="card-box"
                            style="box-shadow:none;padding: 0 0 0 0; width: -webkit-fill-available; border:none; width: -moz-available;"
                            src="{% url 'cal:calendar' %}">
                    </iframe>
                </div>
                {% endif %}
                {% for c in items %}
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<script>
    window.onload = function () {
        var iFrame = document.getElementById('calendar_frame');
        resizeIFrameToFitContent(iFrame);
    };
</script>
{% endblock %}